### ISSUE TITLE
Epic: Complete Machine Learning Workflow

### ISSUE THREAD

**Issue by Benczus** [EKU-Summer-2021/ml-assignment-saidsabri010#1]
As a developer, I want to be able to read datasets from CSV files.
As a developer, I want to be able to use different machine learning models (Decision tree, SVM, K-means) to learn from datasets.
As a developer, I want to be able to automatically plot the output of the prediction or clustering.
As a developer, I want to be able to run the models with parameters from a configuration file.
As a manager, I want to see well formatted outputs saved in CSV files.
As a manager, I want to be able to compare the performance of different models.
As a manager, I want to be able to look at plots visualizing the output of the model.

__AC__:

- [ ] read CSV into pandas dataframe
- [ ] log model runs and solutions
- [ ] plot outputs
- [ ] print best model parameters
- [ ] save run data into directory with separate names

---
__Story Point:__ 5
